---
title: "Reading Question Week 8"
author: "David Murillo"
date: "October 29, 2022"
output:
  html_document:
    theme: cosmo
  html_notebook: default
---

# I worked with Hoa Ninh and Theint Thandar Bol 

## Question

**Q1 (1 pt.): Describe the key difference between the non parametric model (Ch. 7.1) and the parametric model (Ch. 8.1)**

*Answer: In a parametric approach, we need to specify both the deterministic component and the error component, although in some simple cases we may only need to specify the error. In a nonparametric approach we need only to specify the deterministic component, since the error component does not need formal specification.*

**Q2 (1 pt.): What is the difference between interpolation and extrapolation?**

*Answer:  The extrapolation is used when we want to use models to predict values for future observations. And the interpolation is used when we want to predict values within a range of observation already sampled.*

*Interpolation: Help us to estimate the value within the known data set.*

*Extrapolation: Help us to predict the value beyond the known data set.*

**Q3 (1 pt.): Explain why extrapolation has more pitfalls than interpolation.**

*Answer: Extrapolation can be significantly more problematic than interpolation, because in the extrapolation we must have a formal model for the stochastic component. But without a formal model for the stochastic component of the model, it is difficult to provide confidence (prediction) limits on those predictions. We can easily give a point estimate for the prediction – which is the expected value from the deterministic model, but it is much more difficult to give an interval estimate for the prediction.*

*When we perform extrapolation, we may assume that the same pattern that exists inside the current range of data points also exists outside of the range as well. However, this can be a dangerous assumption because it is possible that the pattern that exists outside the current range of data points is quite different.*

*Example 2: We are studying the richness of birds in a coffee plantation. We collected data on coffee plantations of 1, 3, and 7 hectares of coffee area. For 1 hectare we recorded a richness of 5, for 3 hectares a richness of 7, and for 7 hectares a richness of 10 species. We made an interpolation of the richness for 2 hectares and 6 hectares, and we got richness of 6, and 8 respectively, these results made sense and could have a good accuracy. If we extrapolate to know the richness for 12 hectareas, the result of the model is 11 species, and for 20 hectares the richness is 18 species. Now that we have a little knowledge about bird ecology, we know that the richness of birds with coffee area size does not have a linear relationship, so, to improve the accuracy of our model, we use a stochastic model component with poisson distribution. The new model shows that the richness of birds for 12 hectares is 11, but the richness for 20 hectares is 12. What model is the most adequate, this could depend on the techniques that we use to evaluate them.*