---
title: "Lab 03: Data Exploration and Deterministic Functions"
output: html_notebook
author: "David Murillo"
date: "September/21/2022"
---

# Load packages
```{r}

library(psych)
library(here)
```
# Load datasets

```{r}
tabla <- read.csv("data/bird.sta.csv")
```


# Merge data
```{r}
dat_all <- merge(dat_habitat, dat_bird)

plot(ba.tot ~ elev, data = dat_all)
```

Challenge: How could I use R to calculate the total number of waxwings and the number of sites in which they were present?

```{r}
sum(dat_all$CEWA)

subset(dat_all, CEWA > 0)$sta
```
Presence/Absence

```{r}
cewa_present_absent <- as.numeric(dat_all$CEWA >0)

plot(dat_all$elev, cewa_present_absent)
```
Fitting a logistic curve.

```{r}
# Function to calculate the logistic parameter a given the slope and midpoint
get_logistic_param_a = function(slope, midpoint)
{
  b = slope / 4
  return (-midpoint * (slope / 4))
}

# Function to calculate the logistic parameter b given the slope
get_logistic_param_b = function(slope)
{
  return (slope / 4)
}


# Calculate the value of the logistic function at x, given the parameters a and b.
logistic = function(x, a, b)
{
  val = exp(a + b * x)
  return(val / (1 + val))
}

# Calculate the value of the logistic function at x, given a slope and midpoint.
logistic_midpoint_slope = function(x, midpoint, slope)
{
  b = get_logistic_param_b(slope)
  a = get_logistic_param_a(slope, midpoint)
  return(logistic(x, a, b))
}
```

Logistic Fit 1
```{r}
plot(x = dat_all$elev, y = cewa_present_absent)
curve(logistic_midpoint_slope(x, midpoint = 400, slope = 0.1), add = TRUE)
```
Logistic Fit 2
```{r}
plot(x = dat_all$elev, y = cewa_present_absent)
curve(logistic_midpoint_slope(x, midpoint = 400, slope = -0.1), add = TRUE)
```
Logistic Fit 3

```{r}
plot(x = dat_all$elev, y = cewa_present_absent)
curve(logistic_midpoint_slope(x, midpoint = 400, slope = -0.005), add = TRUE)
```

